name: Reusable Gradle CI Pipeline

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          architecture: x64
      - name: Checkout project sources
        uses: actions/checkout@v5
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.3.0
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
